#!/usr/bin/env bash

PROFILE="${SCREEPS_SERVER_PROFILE:-ptr}"
HOME_DIR="${HOME:-/home/vadmin}"

case "${PROFILE}" in
  ptr)
    : "${SCREEPS_PRIVATE_SERVER_DIR:=${HOME_DIR}/screeps_private_server_ptr}"
    : "${SCREEPS_NODE_BIN:=/usr/bin}"
    : "${SCREEPS_SERVER_HOST:=0.0.0.0}"
    : "${SCREEPS_SERVER_PORT:=21035}"
    : "${SCREEPS_CLI_HOST:=localhost}"
    : "${SCREEPS_CLI_PORT:=21036}"
    ;;
  feat-node24)
    # Backward-compatible alternate local install profile.
    : "${SCREEPS_PRIVATE_SERVER_DIR:=${HOME_DIR}/screeps_private_server}"
    : "${SCREEPS_NODE_BIN:=${HOME_DIR}/.local/opt/node24/bin}"
    : "${SCREEPS_SERVER_HOST:=0.0.0.0}"
    : "${SCREEPS_SERVER_PORT:=21025}"
    : "${SCREEPS_CLI_HOST:=localhost}"
    : "${SCREEPS_CLI_PORT:=21026}"
    ;;
  *)
    echo "Unknown SCREEPS_SERVER_PROFILE: ${PROFILE}" >&2
    return 1
    ;;
esac

if [[ -z "${SCREEPS_TAILSCALE_IP:-}" ]] && command -v tailscale >/dev/null 2>&1; then
  SCREEPS_TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | head -n 1 || true)"
fi

: "${SCREEPS_SERVER_URL:=http://${SCREEPS_SERVER_HOST}:${SCREEPS_SERVER_PORT}}"
: "${SCREEPS_SERVER_PUBLIC_HOSTNAME:=${SCREEPS_TAILSCALE_IP:-127.0.0.1}}"
: "${SCREEPS_SERVER_PUBLIC_URL:=http://${SCREEPS_SERVER_PUBLIC_HOSTNAME}:${SCREEPS_SERVER_PORT}}"
: "${SCREEPS_BROWSER_CLIENT_DIR:=${HOME_DIR}/screeps_browser_client}"
: "${SCREEPS_BROWSER_HOST:=127.0.0.1}"
: "${SCREEPS_BROWSER_BIND_HOST:=0.0.0.0}"
: "${SCREEPS_BROWSER_PORT:=8080}"
: "${SCREEPS_BROWSER_URL:=http://${SCREEPS_BROWSER_HOST}:${SCREEPS_BROWSER_PORT}}"
: "${SCREEPS_BROWSER_PUBLIC_HOSTNAME:=${SCREEPS_TAILSCALE_IP:-${SCREEPS_BROWSER_HOST}}}"
: "${SCREEPS_BROWSER_PUBLIC_PORT:=${SCREEPS_BROWSER_PORT}}"
: "${SCREEPS_BROWSER_PUBLIC_URL:=http://${SCREEPS_BROWSER_PUBLIC_HOSTNAME}:${SCREEPS_BROWSER_PUBLIC_PORT}}"
: "${SCREEPS_BROWSER_NODE_BIN:=${HOME_DIR}/.local/opt/node24/bin}"
: "${SCREEPS_LOCAL_TOKEN:=screeps-omega-dev-token}"
: "${SCREEPS_BROWSER_PASSWORD:=screeps-local-pass}"
: "${SCREEPS_PACKAGE_NW:=${SCREEPS_BROWSER_CLIENT_DIR}/vendor/package.nw}"
: "${SCREEPS_BROWSER_SERVER_LIST:=}"

export SCREEPS_SERVER_PROFILE="${PROFILE}"
export SCREEPS_PRIVATE_SERVER_DIR
export SCREEPS_NODE_BIN
export SCREEPS_SERVER_HOST
export SCREEPS_SERVER_PORT
export SCREEPS_SERVER_URL
export SCREEPS_SERVER_PUBLIC_HOSTNAME
export SCREEPS_SERVER_PUBLIC_URL
export SCREEPS_CLI_HOST
export SCREEPS_CLI_PORT
export SCREEPS_BROWSER_CLIENT_DIR
export SCREEPS_BROWSER_HOST
export SCREEPS_BROWSER_BIND_HOST
export SCREEPS_BROWSER_PORT
export SCREEPS_BROWSER_URL
export SCREEPS_BROWSER_PUBLIC_HOSTNAME
export SCREEPS_BROWSER_PUBLIC_PORT
export SCREEPS_BROWSER_PUBLIC_URL
export SCREEPS_BROWSER_NODE_BIN
export SCREEPS_LOCAL_TOKEN
export SCREEPS_BROWSER_PASSWORD
export SCREEPS_PACKAGE_NW
export SCREEPS_BROWSER_SERVER_LIST
export SCREEPS_TAILSCALE_IP
